#include <iostream>
using namespace std;

int main() {
    int choice;
    double num1, num2, result;

    do {
        cout << "===== Calculator =====" << endl;
        cout << "1. Add" << endl;
        cout << "2. Subtract" << endl;
        cout << "3. Multiply" << endl;
        cout << "4. Divide" << endl;
        cout << "5. Exit" << endl;

        cout << "Enter choice: ";
        cin >> choice;

        if (choice >= 1 && choice <= 4) {
            cout << "Enter two numbers: ";
            cin >> num1 >> num2;
        }

        switch (choice) {
            case 1:
                result = num1 + num2;
                cout << fixed << setprecision(2);
                cout << "Result: " << result << endl;
                break;

            case 2:
                result = num1 - num2;
                cout << fixed << setprecision(2);
                cout << "Result: " << result << endl;
                break;

            case 3:
                result = num1 * num2;
                cout << fixed << setprecision(2);
                cout << "Result: " << result << endl;
                break;

            case 4:
                if (num2 == 0) {
                    cout << "Cannot divide by zero." << endl;
                } else {
                    result = num1 / num2;
                    cout << fixed << setprecision(2);
                    cout << "Result: " << result << endl;
                }
                break;

            case 5:
                cout << "Exiting..." << endl;
                break;

            default:
                cout << "Invalid choice." << endl;
        }

        cout << endl;

    } while (choice != 5);


    return 0;
}
